import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/common/Header";

export const metadata: Metadata = {
  title: "About us",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        
      </body>
    </html>
  );
}
